name: Build APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install unzip
      run: sudo apt-get update && sudo apt-get install unzip -y

    - name: Extract project
      run: unzip project.zip -d project

    # 🔥 GENERAR WRAPPER (porque no lo tienes)
    - name: Generate gradle wrapper
      run: |
        cd project/ABootpatch
        gradle wrapper --gradle-version 8.4

    - name: Make gradlew executable
      run: chmod +x project/ABootpatch/gradlew

    - name: Build APK
      run: |
        cd project/ABootpatch
        ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: project/ABootpatch/app/build/outputs/apk/debug/*.apk
