name: Build APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install unzip + gradle
      run: sudo apt-get update && sudo apt-get install unzip gradle -y

    - name: Extract project
      run: unzip project.zip -d project

    - name: Build APK
      run: |
        cd project/ABootpatch
        gradle assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: project/ABootpatch/app/build/outputs/apk/debug/*.apk
